const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/ranchoyin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const url=process.env.PROTOTYPE_URL||'http://127.0.0.1:4174/miniapp-prototype/index.html';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
for(const width of [390,360,1440]){
 const p=await browser.newPage({viewport:{width,height:width===360?740:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(url+'?view=gallery');
 await p.getByRole('button',{name:'产品介绍',exact:true}).click();
 assert.equal(await p.locator('#csComposerInput').inputValue(),'介绍这款产品的核心卖点与使用场景');
 await p.screenshot({path:`/tmp/zrobot-composer-${width}.png`});
 await p.locator('#csComposerInput').fill('周末活动：门店精选商品，9月26日至27日');
 await p.locator('[data-hub="quick-create"]').click();
 await p.locator('#vsPrompt').waitFor({timeout:2500});
 await p.waitForFunction(()=>VisualStudio.getProject().versions.length===1);
 await p.getByRole('button',{name:'改信息',exact:true}).click();
 await p.locator('#vsTextForm [name="title"]').fill('周末活动');
 await p.locator('#vsTextForm [name="subtitle"]').fill('门店精选商品');
 await p.locator('#vsTextForm [name="price"]').fill('¥399');
 await p.locator('#vsTextForm [name="dateText"]').fill('9月26日至27日');
 await p.getByRole('button',{name:'完成',exact:true}).click();
 assert.deepEqual(await p.evaluate(()=>{const d=VisualStudio.getProject().draft;return[d.title,d.subtitle,d.price,d.dateText,d.scene,d.style]}),['周末活动','门店精选商品','¥399','9月26日至27日','gallery','quiet']);
 await p.getByRole('button',{name:'保存版本',exact:true}).click();
 assert.equal(await p.evaluate(()=>VisualStudio.getProject().versions.length),2);
 await p.locator('.vs-records summary').click();
 assert.equal(await p.locator('.vs-user-request').innerText(),'周末活动：门店精选商品，9月26日至27日');
 await p.screenshot({path:`/tmp/zrobot-records-${width}.png`});
 await p.getByRole('button',{name:'查看版本 1',exact:true}).click();
 await p.getByRole('button',{name:'返回创作中心',exact:true}).click();
 await p.locator('#csComposerInput').waitFor({timeout:2500});
 await p.locator('.cs-msg').first().waitFor({timeout:2500});
 assert.match(await p.locator('.cs-msg-q p').first().innerText(),/周末活动/);
 await p.locator('.cs-versions summary').first().click();
 await p.locator('.cs-version-list button').first().waitFor({timeout:2500});
 await p.screenshot({path:`/tmp/zrobot-feed-versions-${width}.png`});
 await p.locator('.cs-version-list button').first().click();
 await p.locator('#vsPrompt').waitFor({timeout:2500});
 await p.getByRole('button',{name:'返回创作中心',exact:true}).click();
 await p.locator('#csComposerInput').waitFor({timeout:2500});
 await p.locator('[data-hub="voice"]').waitFor({timeout:2500});
 await p.locator('.tab[data-route="library"]').click();assert.equal(await p.locator('.ch-material-grid').count(),0);await p.locator('.ch-cover').click();
 await p.getByRole('button',{name:'上屏演示',exact:true}).click();await p.getByRole('button',{name:'查看屏幕',exact:true}).click();
 await p.locator('.tab[data-route="library"]').click();await p.locator('.ch-cover').click();
 await p.getByRole('button',{name:'管理内容',exact:true}).click();
 await p.getByRole('button',{name:'收藏',exact:true}).click();
 await p.getByRole('button',{name:'返回内容库',exact:true}).click();
 await p.getByRole('button',{name:'只看收藏',exact:true}).click();assert.equal(await p.locator('.ch-card').count(),1);
 await p.locator('.tab[data-route="gallery"]').click();
 await p.locator('.cs-gallery .ch-cover').first().click();
 await p.locator('#vsPrompt').waitFor({timeout:2500});
 assert.equal(await p.evaluate(()=>VisualStudio.getProject().draft.title),'让产品成为主角');
 await p.locator('#vsPrompt').fill('突出展示咖啡机');await p.locator('[data-vs="generate"]').click();
 await p.waitForFunction(()=>VisualStudio.getProject().versions.length===1);
 assert.equal(await p.locator('.vs-canvas .vs-art-copy').count(),1);
 await p.getByRole('button',{name:'返回创作中心',exact:true}).click();
 await p.locator('#csComposerInput').waitFor({timeout:2500});
 await p.locator('.tab[data-route="home"]').click();
 await p.locator('[data-route="assistant"]').click();
 await p.locator('#asInput').fill('开始讲解');
 await p.locator('[data-action="as-send"]').click();
 await p.locator('.orb-layer .orb').waitFor({timeout:3000});
 await p.screenshot({path:`/tmp/zrobot-orb-${width}.png`});
 await p.locator('[data-action="orb-close"]').click();
 assert.equal(await p.evaluate(()=>Number(localStorage.getItem('zrobot-credits-v1'))),15);
 await p.getByRole('button',{name:'返回',exact:true}).click();
 await p.locator('.tab[data-route="profile"]').click();
 await p.getByRole('button',{name:'充值',exact:true}).click();
 await p.locator('.cr-plan').first().click();
 assert.equal(await p.evaluate(()=>Number(localStorage.getItem('zrobot-credits-v1'))),75);
 await p.screenshot({path:`/tmp/zrobot-scene-gallery-${width}.png`});
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({width,status:'PASS',flow:'chip fill, composer quick create, auto generate, edits, versions, records, publish, favorite, template'}));await p.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
